---
title: "pl2003_FinalHomeworkCode_01"
output: html_document
date: "2025-02-01"
---

#Challenge 1 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
str= "Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed"
#First I created a vector of the sentence.
str_split (str, " ", simplify = TRUE)
#Then, to extract each 3rd element of the sentence, I repeated the code in multiples of 3. 
str_split_i(str, " ", 3)
str_split_i(str, " ", 6)
str_split_i(str, " ", 9)
str_split_i(str, " ", 12)
str_split_i(str, " ", 15)
str_split_i(str, " ", 18)
str_split_i(str, " ", 21)
```

#Challenge 2
```{r setup, include=FALSE}
#Construct first I copied the given matrix
m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)
x<-m[,c(2,3,6)] #I extracted the 2nd, 3rd, and 6th columns and assigned them to x
x
x<-m[6:8,] #I extracted the 6-8th row and assigned them to variable x 
x<-m[2:6,2:9] #Extracted the elements from row 2, column 2 to row 6, column 9 and assign them to the variable x
```

#Challenge 3
```{r setup, include=FALSE}
#Construct a 4-dimensional, 400 element array 5 x 5 x 4 x 4. Descending series- 400:1 
a <- array(data = 400:1, dim = c(5, 5, 4,4))
a[1, 1, 1, 2]
a[2, 3, 2, ]
a[1:5, 1:5, 3, 3]
```

#Challenge 4
```{r setup, include=FALSE}
#Define the lowest level taxa first 
Catarrhini <- c("Cercopithecidae", "Hylobatidae", "Hominidae")
Platyrrhini <- c("Cebidae", "Atelidae", "Pitheciidae")

#Define the next lowest level taxa 
Anthropoidea <- list (Catarrhini, Platyrrhini) 
names(Anthropoidea) <- list ("Catarrhini", "Platyrrhini")
Anthropoidea

Tarsioidea <- c ("Tarsiidae")

#Define the subcategories  
Haplorhini<- list("Tarsioidea", "Anthropoidea")
names (Haplorhini) <- list ("Tarsioidea", "Anthropoidea" )

Lemuroidea <- c("Cheirogaleidae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")
Lorisoidea <- c("Lorisidae", "Galagidae")
Strepsirhini <- list(Lemuroidea, Lorisoidea)
names (Strepsirhini) <- list("Lemuroidea", "Lorisoidea")

#Define the Highest level 
Primates <- list(Haplorhini, Strepsirhini)
names(Primates) <- list("Haplorhini", "Strepsirhini")
Primates
```

#Challenge 5 
```{r setup, include=FALSE}
#5x3 matrix, ROW-WISE 
m3 <- matrix(data = c(3, 0, 1 ,23, 1, 2, 33, 1, 1, 42, 0, 1, 41, 0, 2), nrow = 5, ncol = 3, byrow = TRUE)
m3
#Coerce the matrix to data frame
df <- data.frame(m3)
colnames(df) <- c("col1", "col2", "col3") #name the columns

df$col2 <- as.logical(df$col2) #coerce the second column to be logical-valued
df$col3 <- as.factor(df$col3) #coerce the third column to be factor-valued
str(df)
```


